# permissions for end users to view calculators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: calculator-viewer-role
rules:
- apiGroups:
  - apps.example.com
  resources:
  - calculators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.example.com
  resources:
  - calculators/status
  verbs:
  - get
